In [24]:
import pandas as pd

location = './data'
file2010 = '.\data\처방조제수_2010~.xls'
file2013 = '처방조제수_2013~.xls'
file2016 = '처방조제수_2016~.xls'
file2019 = '처방조제수_2019~.xls'
file2022 = '처방조제수_2022~.xls'

data = pd.read_excel(file2010)
row_data = data.iloc[5]
main_index = row_data.tolist()
row_data = data.iloc[6]
sub_index = row_data.tolist()
row_data = data.iloc[7]
colum_1 = row_data.tolist()
row_data = data.iloc[8]
colum_2 = row_data.tolist()

arrays1 = [main_index,sub_index]
arrays2 = [colum_1,colum_2]
tuples = list(zip(*arrays1))
data_tuples = list(zip(*arrays2))
index = pd.MultiIndex.from_tuples(tuples)
columns = pd.MultiIndex.from_tuples([('직접조제', '명','개','원'), ('처방조제', '명','개','원')])
df = pd.DataFrame(data_tuples, index=index, columns=columns)
df

                    직접조제       처방조제
                       명          명
                       개          개
                       원          원
기간명       직접처방 구분   직접조제       처방조제
2010년 01월 환자수         88     18,439
          수량       5,052  3,146,476
          사용금액       342    748,611
2010년 02월 환자수         77     17,620
...                  ...        ...
2012년 11월 수량       4,020  3,836,052
          사용금액       258    797,215
2012년 12월 환자수         67     20,210
          수량       3,871  3,752,349
          사용금액       246    790,157

[109 rows x 2 columns]